# Generated by Django 5.0.6 on 2026-04-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0009_merge_0006_alter_blog_slug_0008_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="featured_image",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
