# Generated by Django 5.0.6 on 2026-04-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0010_alter_blog_featured_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="featured_image",
            field=models.ImageField(upload_to="blog_images/"),
        ),
    ]
